### ISSUE TITLE
[FEATURE/jwt-login] security + jwt 를 이용한 자체 로그인

### ISSUE THREAD

**Issue by JGoo99** [SamCoMo/DBZ-Backend#23]
## 💡 Description

spring security 프레임워크와 json web tokens (JWT) 을 이용한 로그인 기능을 구현합니다.

<br/>

**JSON 이란?**

**[개념 & 구성]**

JWT 는 회원 정보와 같은 중요한 정보를 주고받을 때 암호화 하여 주고받는 토큰입니다.
주로 회원의 권한을 **인증**하고 접근을 **인가**하는 과정에 사용됩니다. (이 외에도 정보를 교환할 때도 사용합니다!)

토큰의 구성은 `.` 을 기준으로 header, payload, signature 로 이루어져있는데 각 파트에 들어가는 정보가 다릅니다.
저는 아래처럼 사용할 예정입니다!

- header : 알고리즘 종류(HS256), 토큰 타입(JWT)
- payload : 토큰종류(access or refresh), 이메일, 토큰만료시간
- signature : 암호키(사용자지정)

```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
```
사람 눈으로는 전혀 알아볼 수 없는 형태의 문자열로 이루어져있습니다.
하지만 누군가 토큰을 탈취하여 해석한다면 header와 payload 의 내용을 확인할 수 있으므로 민감하지 않은 정보만 담아야 합니다.

**[인증 로직]**

```
- 기존 회원이 인증과정을 거쳐 로그인에 성공한다.
- accessToken과 RefreshToken 를 발급한다.
```

**[인가 로직]**

```
- 클라이언트에서 헤더에 accessToken(로그인 시 발급받음) 을 담아 특정 api 에 접근을 요청한다.
- 서버에서 accessToken 를 복호화하여 회원정보와 토큰 만료기간이 유효한지 검증한다.
- 검증과정을 통과하면 접근을 허가한다.
```

<br/>

## 🚗 Todo

- [x] JwtUtil : jwt 정보 복호화, jwt 토큰 생성
- [x] JwtFilter : 로그인한 유저가 접근 시 해당 토큰이 유효한지 검증
- [x] LoginFilter : 로그인 시 성공하면 jwt 발급
- [x] SecurityConfig : 커스텀 필터 (JwtFilter, LoginFilter)를 등록

<br/>

## 🐶 Technology Stack

> **JWT**
>
> SWT(Simple Web Tokens) 및 SAML(Security Assertion Markup Language Tokens) 보다 훨씬 길이가 짧다.
>
> 또한 key-value 로 정보가 저장되므로 정보를 가져와 사용하는 것에 있어서 편리하다.

<br/>
## 📚 References

[jwt.io](https://jwt.io/)
[jwt doc](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/oauth2/jwt/Jwt.html)

**Comment by Cassiiopeia** [comment]
궁금한것이 있습니다.

Spring Security로 회원 검증을할때 
      Authentication authentication 을 Header로 받아서
      
      authentication.getId() 아니면 getEmail() 이런식으로 구현하시나요?

**Comment by JGoo99** [comment]
로그인 이후 특정 api 에 접근할 때의 인가과정을 말씀하신 것 맞나요??

헤더에 담긴 accessToken 을 받아와서 JwtUtil.java 커스텀 클래스에서 복호화합니다.
복호화 할 때 토큰에 담긴 tokenType, email, role, 만료여부를 가져올 수 있어요.

따라서 authentication.getname() 이 아닌 jwtUtil.getEmail() 이런식으로 진행할 예정입니다.
혹시 다른 질문이었다면 답장 부탁드려요!
