### ISSUE TITLE
[TODO/CHAT] 채팅서비스 로직 수정 피드백 현황

### ISSUE THREAD

**Issue by Cassiiopeia** [SamCoMo/DBZ-Backend#32]
### ChatMessage에 Content 누락
---

```
    ChatMessage chatMessage = ChatMessage.builder()
        .chatRoomId(chatRoomId)
        .senderId(senderId)
        .recipientId(chatRoom.getRecipientId())
        .imageUrlList(null) //TODO : S3연결 작업필요
        .createdAt(LocalDateTime.now())
        .build();
```

```
    ChatMessage chatMessage = ChatMessage.builder()
        .chatRoomId(chatRoomId)
        .senderId(senderId)
        .recipientId(recipientId)
        .content(request.getContent()) // Content 추가
        .imageUrlList(null) //TODO : S3연결 작업필요
        .createdAt(LocalDateTime.now())
        .build();
```
수정했습니다 ^^ 세상에나 메시지에 메시지내용이 빠져있었네요...
감사합니다.

### ChatMessage에 recipientId 와 senderId의 혼동

먼저 채팅방이 생성되는 로직은 다음과 같습니다.
member1이 로그인되어있을때 member2와 채팅할 채팅방을 생성하면

ChatRoom에 대한
senderId = "member1",
recipientId= "member2"

로 설정됩니다.

냉정하게 둘을 구분할 필요는없습니다.
senderId 와 recipientId를 명시하는것보다 
member1과 member2로 나타내는게 맞는것같습니다. 

문제는 이부분에서 생기는데요
member2가 로그인되어있을때 member1와 채팅하려고합니다.
그럼 getOrCreateChatRoom() 메소드를 통해 채팅방을 얻는데요

ChatRoomId는 중복될수없으니 이미 존재하는 ChatRoom을 반환합니다.
그렇게되면 안에 값은 변함이 없이 
senderId = "member1",
recipientId= "member2" 가됩니다.

이렇게되면 메시지를 보낼때 sender와 recipientId를 명시할때 
chatRoom에서 가져오면안됩니다. sender와 recipientId를 바꿔서 보내야하는데요.

다음과 같이 해결해보았습니다.

```
// sender 와 recipient 구분하기
String recipientId = senderId.equals(chatRoom.getSenderId()) ? chatRoom.getRecipientId() : chatRoom.getSenderId();

```
하지만 이렇게 수정했더니 의문점이 생깁니다.
PUB / SUB을 사용해서 구현하였으므로 메시지를 게시할때 구독하는 주소는 /chatrooms/{채팅방아이디} 였습니다. 

이렇게되면 굳이 recipientId 를 ChatRoom에 필요가없습니다.
채팅방주소를 구독하고있는 Member들은 recipient 관계로 알수있는것이 아니라 ChatRoomId에 대해서만 관계가 있는것이니까요

아래는 수정된 Entity 구조입니다.

        public class ChatRoom {
          @Id
          private String chatRoomId;
          // sender, recipient 관계 삭제
          Set<String> memberIdList; // 채팅방에 속해있는 Member관리
          private String lastChatMessageContent;
          private LocalDateTime lastChatMessageAt;
        }

ChatRoom에 
Set<String> memberIdList; 
을 추가하여 채팅방에 속해있는 멤버를 관리할수있습니다.

회원 목록을 사용함으로써 두가지 이점이있습니다.

1. 회원 목록을 사용 -> 채팅 시스템을 1대1 채팅 ->  다대다 채팅으로 쉽게 확장 가능
2. 유연성: 회원를 채팅방에 추가, 제거하는 것이 용이합니다.

#### Set<String> 에 대한 이모저모
---

저희가 MariaDB나 MySQL같은 RDBMS를 사용하였을때 Entity내부에 Set<String> MemberIdLIst를 생성하면 RDBMS에서 직접적으로 이부분을 지원하지않습니다. 

JPA는 이러한 관계형 데이터베이스에 테이블간의 관계를 생성시키게 도와줍니다.
중간 역할을 하는 테이블을 만들어 다대다 관계를 구현하는데요

ChatRoomMemberId 테이블을 만들어 ChatRoom과 MemberId의 관계를 나타내며 안쪽에는 ChatRoomId와 MemeberId의 외래키를 포함시킵니다.

하지만!

MongoDB는 @Document이라는 어노테이션을 사용하여 Entity를 생성하는 문서지향 데이터베이스입니다. 비정규화를 통해 중복을 허용합니다. 
Set<String> 또는 배열과 같은 타입을 직접적으로  저장합니다.
별도의 테이블과 외래키를 생성하지않고 ChatRoom안에 배열을 저장합니다.

### @Transactional(readOnly = true) 을 사용하는 이유
---
스프링에서 지원하는 트랜잭션 관리기능입니다. 데이터 읽기. 조회에 사용합니다.
1. 성능 최적화 : 읽기 전용이기때문에 Lock기능 과 같은 변경기능을 활용하지않습니다.  일부데이터에 대한 읽기 전용쿼리를 최적화 시켜서 빠른 응답시간을 가진다고합니다.
2. 데이터 일관성 유지 : 해당 트랜잭션내에서 데이터변경이 발생할때 예외가 발생합니다.
3. 가독성 향샹: @Transactional(readOnly = true) 이 붙어있으면 해당 메서드나 클래스가 데이터를 변경하지 않는다는것을 알수있어 가독성이 좋아집니다. 

###  updateChatRoomInfo() 메소드의 명명법
---

해당부분은 ChatRoom의 
마지막 메시지 Content와 
마지막 메시지 시간을 업데이트하는 로직입니다. 
메소드이름과 구현로직이 맞지않아 updateLastChatInfo() 로 변경하겠습니다.

###  채팅방 -> 채팅내역 조회시 페이징 기능추가
---

채팅내역이 굉장히 많을때 성능문제가 발생할수있습니다. 최신 메시지순으로 페이징해서 받아올수있게 수정하겠습니다.

### 채팅방 -> 채팅내역 조회시 List형식으로 가져올때 Optional<> 삭제
---

Optional<List<ChatMessage>> findByChatRoomId(String chatRoomId);

기존코드는 채팅메시지를 가져올때 Optional형식으로 가져와 만약 존재하지 않을시 채팅메시지를 찾을수없다는 에러메시지를 반환했었습니다.

하지만 채팅메시지가 존재하지않을때 굳이 에러메시지를 반환할 필요가없을뿐더러
빈 List값으로 와 null 체크가 없어도될것같습니다.

### JWT 로그인 구현
---

현재 JWT에서 멤버 ID를 가져오는것이 임시로 작성되어있습니다. 해당 기능을 추후에 추가하겠습니다.

### API명세 엔드포인트 주소 수정
---

도메인과 로직에 대한 통일성을 위한 엔드포인트 주소 개선이 필요할것같습니다.

### 회원에 대한 채팅방리스트를 가져올때 정렬처리
---

List<ChatRoom> findBySenderIdOrRecipientId(String userId, String userId1);

현재 이렇게 되어있는데 일단 ChatRoom은 Set<String> MemberIdList로 수정할것이기때문에 전체부분이 바뀔것같습니다.

마지막 ChatMessage 생성날짜 기준으로 최근순으로 채팅방 리스트를 불러오는 로직으로 수정하겠습니다.

### ChatMessage의 @Id값 명명 수정
---

기존
private String id; 에서
private String chatMessageId; 로 수정하겠습니다.

### MongoDB에서 @Id값을 String을 사용하는이유
---

https://codinghack.tistory.com/97 
```
다음을 보면 이해가 갈 수 있습니다. 
ObjectId는 "_id"의 기본 데이터형이다. 
ObjectId 클래스는 경량으로 설계됐으면서도 여러 장비에 걸쳐 전역적으로 유일한 방법으로 생성하기도 쉽다. 
자동 증가하는 기본 키처럼 전통적인 것이 아닌 ObjectId를 사용하는 주요 이유는 몽고DB의 분산 특성 떄문이다. 
여러 서버에 걸쳐 자동으로 증가하는 기본 키를 동기화 하는 작업은 어렵고 시간이 걸린다. 
몽고DB는 분산 데이터베이스로 설계됐기 때문에 샤딩된 환경에서 고유 식별자를 생성하는 것이 매우 중요했다. 

ObjectId는 12바이트 스토리지를 사용하며 24자리 16진수 문자열 표현이 가능하다. 
바이트당 2자리를 사용한다. 여러개의 새로운 ObjectId를 연속으로 생성하면 매번 마지막 숫자 몇개만 바뀐다. 
몇 초 간격을 두고 생성하면 중간 숫자 몇개가 바뀐다. 이는 생성되는 방식 때문이다.

ObectId의 첫 4바이트는 타임스탬프다. 
1970년 1월 1일부터의 시간을 1/1000초 단위로 저장하는 타임스탬프이며 유용한 속성을 제공한다. 
타임스탬프는 4바이트 이후 뒤의 값 5바이트~ 묶일 때 초단위의 유일성을 제공한다.

타임스탬프가 맨 처음에 온다는 것은 ObjectId가 대략 입력 순서대로 정렬된다는 의미다. 
이는 확실히 보장되지는 않지만 효율적으로 인덱싱하는 특성이 있다.

 다음 5바이트는 랜덤 값이다. 
최종 3바이트는 서로 다른 시스템에서 충돌하는 ObjectId들을 생성하지 않도록 랜덤 값으로 시작하는 카운터다. 
ObjectId의 앞 9바이트는 1초 동안 여러 장비와 프로세스에 걸쳐 유일성을 보장한다.

 마지막 3바이트는 단순히 증분하는 숫자로 1초 내 단일 프로세스의 유일성을 보장한다. 
고유한 ObjectId는 프로세스당 1초에 256^3(1677만7216)개까지 생성된다.

 도큐먼트를 입력할 때 "_id" 키를 명시하지 않으면 키가 자동으로 추가된다. 
이는 몽고DB 서버에서 관리할 수 있지만 일반적으로 클라이언트 쪽 드라이버에서 관리한다.
```
이런의미에서 MongoDB는 순차적으로 올라가는 숫자형태의 ID값이 아닌 보통 String으로 관리합니다.

- [ ] ChatMessage에 Content 누락
- [ ] ChatMessage에 recipientId 와 senderId의 혼동
- [ ] updateChatRoomInfo() 메소드의 명명법
- [ ] 채팅방 -> 채팅내역 조회시 페이징 기능추가
- [ ] 채팅방 -> 채팅내역 조회시 List형식으로 가져올때 Optional<> 삭제
- [ ] JWT 로그인 구현
- [ ] API명세 엔드포인트 주소 수정
- [ ] 회원에 대한 채팅방리스트를 가져올때 정렬처리
- [ ] ChatMessage의 @Id값 명명 수정
